### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by robinbolton** [gkz/LiveScript-style-guide#10]
Why does the style guide specify 4 spaces per indentation level as the standard but then proceed to use 2 spaces in all but one of the examples?  The same appears to be true with the main LiveScript site, which uses 2 spaces in all examples.

**Comment by gkz** [comment]
I just recently changed the style guide to specify 4 spaces rather than 2. It will take a while to update everything.

**Comment by robinbolton** [comment]
Thanks for clarifying.  It might also be useful to provide reasoning for that decision in the style guide, as there seems to be a lot of back-and-forth on the 2 vs. 4 spaces.  Personally I prefer 2 spaces, but given that you've written considerably more LS code than I have I'd like to know the official opinion.

**Comment by raine** [comment]
https://github.com/gkz/LiveScript/commit/665339acd43804fab5544f6e825cfe2fa5401369#commitcomment-11068894
